In [26]:
import numpy as np
import pandas as pd 
import statsmodels.api as sm
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import warnings
warnings.filterwarnings('ignore')

In [27]:
df=pd.read_csv('./data/processed/clean-ames-housing.csv',keep_default_na=False)

In [28]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,8.062258,8450,Pave,NA,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NA,Attchd,2000-2010,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NA,NA,NA,0,2,2008,WD,Normal,12.247699
1,2,20,RL,8.944272,9600,Pave,NA,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1950-2000,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NA,NA,NA,0,5,2007,WD,Normal,12.109016
2,3,60,RL,8.246211,11250,Pave,NA,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2000-2010,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NA,NA,NA,0,9,2008,WD,Normal,12.317171
3,4,70,RL,7.745967,9550,Pave,NA,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1950-2000,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NA,NA,NA,0,2,2006,WD,Abnorml,11.849405
4,5,60,RL,9.165151,14260,Pave,NA,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000-2010,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NA,NA,NA,0,12,2008,WD,Normal,12.429220

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
x_cat=df[['ExterQual','Neighborhood','KitchenQual']].copy()

In [30]:
x_cat['ExterQual'].unique()

array(['Gd', 'TA', 'Ex', 'Fa'], dtype=object)

In [31]:
x_cat['Neighborhood'].unique()

array(['CollgCr', 'Veenker', 'Crawfor', 'NoRidge', 'Mitchel', 'Somerst',
       'NWAmes', 'OldTown', 'BrkSide', 'Sawyer', 'NridgHt', 'NAmes',
       'SawyerW', 'IDOTRR', 'MeadowV', 'Edwards', 'Timber', 'Gilbert',
       'StoneBr', 'ClearCr', 'NPkVill', 'Blmngtn', 'BrDale', 'SWISU',
       'Blueste'], dtype=object)

In [32]:
x_cat['KitchenQual'].unique()

array(['Gd', 'TA', 'Ex', 'Fa'], dtype=object)

In [33]:
qual_order=['Fa','TA','Gd','Ex' ]
ord_encoder=OrdinalEncoder(categories=[qual_order,qual_order])
x_cat[['ExterQual_enc','KitchenQual_enc']]=ord_encoder.fit_transform(x_cat[['ExterQual','KitchenQual']])

In [34]:
x_dummies=pd.get_dummies(x_cat['Neighborhood'],prefix='nbhd',drop_first=True,)

In [35]:
x=pd.concat([
    x_cat[['ExterQual_enc','KitchenQual_enc']],
    df[['OverallQual', 'GrLivArea', 'GarageCars', 'TotalBsmtSF' ]],
    x_dummies],axis=1
)

In [36]:
x.head()

,ExterQual_enc,KitchenQual_enc,OverallQual,GrLivArea,GarageCars,TotalBsmtSF,nbhd_Blueste,nbhd_BrDale,nbhd_BrkSide,nbhd_ClearCr,nbhd_CollgCr,nbhd_Crawfor,nbhd_Edwards,nbhd_Gilbert,nbhd_IDOTRR,nbhd_MeadowV,nbhd_Mitchel,nbhd_NAmes,nbhd_NPkVill,nbhd_NWAmes,nbhd_NoRidge,nbhd_NridgHt,nbhd_OldTown,nbhd_SWISU,nbhd_Sawyer,nbhd_SawyerW,nbhd_Somerst,nbhd_StoneBr,nbhd_Timber,nbhd_Veenker
0,2.0,2.0,7,1710,2,856,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,1.0,1.0,6,1262,2,1262,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,2.0,2.0,7,1786,2,920,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,1.0,2.0,7,1717,3,756,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,2.0,2.0,8,2198,3,1145,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False

In [37]:
y=df['SalePrice'].copy()

In [38]:
from sklearn.preprocessing import StandardScaler
x_train_ols,x_test_ols,y_train_ols,y_test_ols=train_test_split(x,y,test_size=0.2,random_state=39)
x_train_ols=x_train_ols.reset_index(drop=True)
x_test_ols=x_test_ols.reset_index(drop=True)
y_train_ols=y_train_ols.reset_index(drop=True)
y_test_ols=y_test_ols.reset_index(drop=True)

sds=StandardScaler()
x_train_ols=sds.fit_transform(x_train_ols)
x_test_ols=sds.transform(x_test_ols)
x_train_ols=pd.DataFrame(x_train_ols,columns=x.columns)
x_test_ols=pd.DataFrame(x_test_ols,columns=x.columns)

In [39]:
x_train_ols=sm.add_constant(x_train_ols)
model=sm.OLS(y_train_ols,x_train_ols).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.883
Model:                            OLS   Adj. R-squared:                  0.880
Method:                 Least Squares   F-statistic:                     284.3
Date:                Mon, 31 Aug 2026   Prob (F-statistic):               0.00
Time:                        20:03:22   Log-Likelihood:                 676.68
No. Observations:                1163   AIC:                            -1291.
Df Residuals:                    1132   BIC:                            -1135.
Df Model:                          30
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              12.0332      0.004   2993.868      0.000      12.025      12.041
ExterQual_enc       0.0122      0.007      1.731      0.084      -0.002       0.026
KitchenQual_enc     0.0444      0.006      7.117      0.000       0.032       0.057
OverallQual         0.1066      0.007     14.222      0.000       0.092       0.121
GrLivArea           0.1226      0.005     22.354      0.000       0.112       0.133
GarageCars          0.0544      0.006      9.548      0.000       0.043       0.066
TotalBsmtSF         0.0685      0.005     12.947      0.000       0.058       0.079
nbhd_Blueste       -0.0007      0.004     -0.169      0.866      -0.009       0.008
nbhd_BrDale        -0.0141      0.005     -2.579      0.010      -0.025      -0.003
nbhd_BrkSide        0.0010      0.008      0.119      0.905      -0.015       0.017
nbhd_ClearCr        0.0248      0.006      3.995      0.000       0.013       0.037
nbhd_CollgCr        0.0267      0.011      2.393      0.017       0.005       0.049
nbhd_Crawfor        0.0314      0.008      4.117      0.000       0.016       0.046
nbhd_Edwards        0.0041      0.010      0.424      0.672      -0.015       0.023
nbhd_Gilbert        0.0266      0.009      2.880      0.004       0.008       0.045
nbhd_IDOTRR        -0.0303      0.007     -4.159      0.000      -0.045      -0.016
nbhd_MeadowV       -0.0113      0.006     -1.944      0.052      -0.023       0.000
nbhd_Mitchel        0.0137      0.007      1.831      0.067      -0.001       0.028
nbhd_NAmes          0.0198      0.014      1.460      0.144      -0.007       0.046
nbhd_NPkVill        0.0003      0.005      0.064      0.949      -0.009       0.010
nbhd_NWAmes         0.0162      0.009      1.837      0.066      -0.001       0.033
nbhd_NoRidge        0.0198      0.007      2.811      0.005       0.006       0.034
nbhd_NridgHt        0.0319      0.009      3.564      0.000       0.014       0.049
nbhd_OldTown       -0.0293      0.010     -2.836      0.005      -0.050      -0.009
nbhd_SWISU          0.0029      0.006      0.465      0.642      -0.009       0.015
nbhd_Sawyer         0.0133      0.009      1.491      0.136      -0.004       0.031
nbhd_SawyerW        0.0104      0.008      1.338      0.181      -0.005       0.026
nbhd_Somerst        0.0270      0.009      3.045      0.002       0.010       0.044
nbhd_StoneBr        0.0194      0.006      3.318      0.001       0.008       0.031
nbhd_Timber         0.0205      0.007      2.902      0.004       0.007       0.034
nbhd_Veenker        0.0173      0.005      3.514      0.000       0.008       0.027
==============================================================================
Omnibus:                      215.320   Durbin-Watson:                   2.032
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              755.275
Skew:                          -0.875   Prob(JB):                    9.86e-165
Kurtosis:                       6.539   Cond. No.                         17.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [40]:
df.select_dtypes(include='object').columns

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC',
       'Fence', 'MiscFeature', 'SaleType', 'SaleCondition'],
      dtype='object')

In [41]:
df.select_dtypes(include='number').columns

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold', 'SalePrice'],
      dtype='object')

In [42]:
df['MSSubClass']=df['MSSubClass'].astype('object')

### Features Classification

In [43]:
numeric_features=['LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond' , 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal']


ExtKitHeat_features=['ExterQual', 'KitchenQual','ExterCond','HeatingQC']
ExtKitHeat_qual=['Po','Fa', 'TA','Gd', 'Ex']

LotShape_feature=['LotShape']
LotShape_order=['Reg', 'IR1', 'IR2', 'IR3']

BsFpGarPol_features=['BsmtQual','FireplaceQu','GarageQual','PoolQC','BsmtCond','GarageCond']
BsFpGarPol_qual=['NA','Po','Fa', 'TA','Gd', 'Ex']

bsmt_exposure_fetaure=['BsmtExposure']
bsmt_exposure_order=['No', 'NA', 'Mn', 'Av', 'Gd']

bsmt_finish_features=[ 'BsmtFinType1','BsmtFinType2']
bsmt_finish_order=['NA', 'Unf', 'LwQ', 'Rec', 'BLQ', 'ALQ', 'GLQ']

functional_feature=['Functional']
functional_order=['Sal','Sev','Maj2','Maj1', 'Mod','Min2','Min1','Typ']

grage_finish_feature=['GarageFinish']
grage_finish_order=['NA', 'Unf','RFn', 'Fin' ]

paveddrive_feature=['PavedDrive']
paveddrive_order=['N', 'P','Y']

fence_feature=['Fence']
fence_order=['NA', 'MnWw', 'GdWo', 'MnPrv', 'GdPrv']

utilities_feature=['Utilities']
utilities_order=['ELO','NoSeWa','NoSewr','AllPub' ]

landslope_feature=['LandSlope']
landslope_order=['Sev','Mod','Gtl' ]

GarageYrBlt_feature=['GarageYrBlt']
GarageYrBlt_order= ['NA', '1900-1950', '1950-2000', '2000-2010', '2010-2025']



nominal_features=['Condition1', 'Condition2','BldgType','HouseStyle','MSZoning',
       'Street','Alley','LandContour','LotConfig', 'Neighborhood','RoofStyle',
       'RoofMatl','Exterior1st','Exterior2nd','MasVnrType','Foundation','Heating',
       'CentralAir', 'Electrical','MiscFeature','SaleType', 'SaleCondition','GarageType',
       'MSSubClass']

In [44]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,StandardScaler
preprocessor=ColumnTransformer([
    ('num',StandardScaler(),numeric_features),
    ('ExtKitHeat',Pipeline([
        ('encode',OrdinalEncoder(categories=[ExtKitHeat_qual]*len(ExtKitHeat_features))),
        ('scale', StandardScaler())]),
        ExtKitHeat_features),
    
    ('LotShape',Pipeline([
        ('encode',OrdinalEncoder(categories=[LotShape_order]*len(LotShape_feature))),
        ('scale',StandardScaler())]),
        LotShape_feature),
    
    ('BsFpGarPol',Pipeline([
        ('encode',OrdinalEncoder(categories=[BsFpGarPol_qual]*len(BsFpGarPol_features))),
        ('scale',StandardScaler())]),
        BsFpGarPol_features),
     
    ('bsmt_exposure',Pipeline([
        ('encode',OrdinalEncoder(categories=[bsmt_exposure_order]*len(bsmt_exposure_fetaure))),
        ('scale',StandardScaler())]),
        bsmt_exposure_fetaure),
    
    ('bsmt_finish',Pipeline([
            ('encode',OrdinalEncoder(categories=[bsmt_finish_order]*len(bsmt_finish_features))),
            ('scale',StandardScaler())]),
            bsmt_finish_features),
    
    ('functional',Pipeline([
                ('encode',OrdinalEncoder(categories=[functional_order]*len(functional_feature))),
                ('scale',StandardScaler())]),
                functional_feature),
    ('grage_finish',Pipeline([
                ('encode',OrdinalEncoder(categories=[grage_finish_order]*len(grage_finish_feature))),
                ('scale',StandardScaler())]),
                grage_finish_feature),
    
    ('paveddrive',Pipeline([
                ('encode',OrdinalEncoder(categories=[paveddrive_order]*len(paveddrive_feature))),
                ('scale',StandardScaler())]),
                paveddrive_feature),
       
    ('fence',Pipeline([
                ('encode',OrdinalEncoder(categories=[fence_order]*len(fence_feature))),
                ('scale',StandardScaler())]),
                fence_feature),
    
    ('utilities',Pipeline([
                ('encode',OrdinalEncoder(categories=[utilities_order]*len(utilities_feature))),
                ('scale',StandardScaler())]),
                utilities_feature),
    
    ('landslope',Pipeline([
                ('encode',OrdinalEncoder(categories=[landslope_order]*len(landslope_feature))),
                ('scale',StandardScaler())]),
                landslope_feature),
    
    ('GarageYrBlt',Pipeline([
                ('encode',OrdinalEncoder(categories=[GarageYrBlt_order]*len(GarageYrBlt_feature))),
                ('scale',StandardScaler())]),
                GarageYrBlt_feature),

    ('nom',OneHotEncoder(drop='first',handle_unknown='ignore'),nominal_features)
])

In [45]:
from sklearn.linear_model import LinearRegression, Lasso
pipe=Pipeline([
    ('preprocessing',preprocessor),
    ('model',Lasso(alpha=0.01))
])

In [46]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
x=df.drop(columns=['SalePrice'])
y=df['SalePrice']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=56)
pipe.fit(x_train,y_train)
y_pred=pipe.predict(x_test)

In [47]:
r2=r2_score(y_test,y_pred)
print(f'The R2 Score of the Linear Model is {r2}')
n=x_test.shape[0]
X_trasnformed=preprocessor.fit_transform(x_train)
print(f'The number of features in the transformed dataset is {X_trasnformed.shape[1]}')
p=X_trasnformed.shape[1]
Adj_r2=1-((1-r2)*(n-1)/(n-p-1))
print(f'The Adjusted R2 Score of the Linear Model is {Adj_r2}')

The R2 Score of the Linear Model is 0.8841606595066804
The number of features in the transformed dataset is 206
The Adjusted R2 Score of the Linear Model is 0.600078467344492

In [48]:
coef=pipe.named_steps['model'].coef_
transformed_columns=pipe.named_steps['preprocessing'].get_feature_names_out()

In [49]:
lasso_coef_df=pd.DataFrame(data={
    'Features':transformed_columns,
    'Coefficients':coef
})
lasso_coef_df[abs(lasso_coef_df['Coefficients'])>0].count()

Features        31
Coefficients    31
dtype: int64

In [50]:
lasso_coef_df[abs(lasso_coef_df['Coefficients'])>0]

                       Features  Coefficients
0              num__LotFrontage      0.014497
1                  num__LotArea      0.014309
2              num__OverallQual      0.091236
3              num__OverallCond      0.022705
5               num__BsmtFinSF1      0.024408
8              num__TotalBsmtSF      0.028880
9                 num__1stFlrSF      0.014048
11            num__LowQualFinSF     -0.001810
12               num__GrLivArea      0.113732
13            num__BsmtFullBath      0.002530
15                num__FullBath      0.011721
16                num__HalfBath      0.007666
18            num__KitchenAbvGr     -0.008477
20              num__Fireplaces      0.009173
21              num__GarageCars      0.018965
22              num__GarageArea      0.019021
23              num__WoodDeckSF      0.009117
27             num__ScreenPorch      0.002172
30        ExtKitHeat__ExterQual      0.016087
31      ExtKitHeat__KitchenQual      0.025230
33        ExtKitHeat__HeatingQC      0.018048
34           LotShape__LotShape      0.006427
35         BsFpGarPol__BsmtQual      0.019410
36      BsFpGarPol__FireplaceQu      0.008321
41  bsmt_exposure__BsmtExposure      0.011681
42    bsmt_finish__BsmtFinType1      0.011578
44       functional__Functional      0.018342
45   grage_finish__GarageFinish      0.013843
46       paveddrive__PavedDrive      0.012621
50     GarageYrBlt__GarageYrBlt      0.017304
80             nom__MSZoning_RM     -0.016979